apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pavestack
  namespace: argocd
spec:
  description: Pavestack production workloads
  sourceRepos:
    - https://github.com/pavestack/pavestack.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: kyverno.io
      kind: ClusterPolicy
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
