{{- if .Values.secrets.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "service-template-api.fullname" . }}
  labels:
    {{- include "service-template-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "service-template-api.fullname" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.externalSecret.key | quote }}
{{- end }}
