apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "service-template-api.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "service-template-api.labels" . | nindent 4 }}
automountServiceAccountToken: false
