name: monorepo-security

on:
  pull_request:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read

jobs:


  trivy-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 1

  checkov-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true
          soft_fail: true

  tflint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform-infra
    steps:
      - uses: actions/checkout@v7
      - uses: terraform-linters/setup-tflint@v6
      - name: TFLint init
        run: tflint --init
      - name: TFLint scan
        run: tflint --recursive
